### ISSUE TITLE
Projection for polygons passed to fetch_ldc_spatial?

### ISSUE THREAD

**Issue by gregor-fausto** [Landscape-Data-Commons/trex#13]
Thanks for this great package! Our team at the USGS recently met with @smccord about `terradactyl` and `trex`, and are starting to explore its functionality. 

What spatial projection should be used for the polygons that are passed to `fetch_ldc_spatial`?

**Comment by nstauffer** [comment]
The function internally reprojects incoming polygons to match the points coming from the LDC, so it shouldn't matter what projection they're in. But "shouldn't" doesn't mean "doesn't"! If you're getting an error of some kind, I'd love to know about it.

**Comment by gregor-fausto** [comment]
I've been working with the function this week and I think it's acting like you described. I see that it's doing that here https://github.com/Landscape-Data-Commons/trex/blob/59aa029954d745abfe058e716172527dc66eb7f0/R/ldc.R#L461-L467, reprojecting the input polygon to NAD83. Makes sense and hasn't given me any issues, so I'll close this. Thank you!
